### ISSUE TITLE
R3 Design Files

### ISSUE THREAD

**Issue by birolsari** [jrsikken/AEMLION#2]
I dont find R3 design files , How can I find it ?

**Comment by jrsikken** [comment]
On https://github.com/jrsikken/AEMLION
Press the button View Code

**Comment by birolsari** [comment]
I saw that but ı found just AEMLION-R2.brd board ı didnt see R3 board

**Comment by jrsikken** [comment]
My bad. I will upload in 24hrs and let you know here

**Comment by jrsikken** [comment]
I have uploaded R3 files
